[build]
  command = "echo 'window.env = { TMDB_API_KEY: \"${TMDB_API_KEY}\", OPENAI_API_KEY: \"${OPENAI_API_KEY}\" }' > env.js"

[redirects]
  [[redirects]]
    from = "/"
    to = "/html/index.html"
    status = 200
